networks:
  dev:
services:
  postgres-pr:
    image: postgres:17
    container_name: postgres_container-pr
    env_file:
      - postgres.env
    ports:
      - "5433:5432"
    networks:
      dev:


  backend-pr:
    image: andreyparkh/my-calendar-backend-pr:latest
    container_name: family-hub-backend-pr
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    env_file:
      - backend.env
    networks:
      dev:


  frontend-pr:
    image: andreyparkh/my-calendar-frontend-pr:latest
    container_name: family-hub-frontend-pr
    ports:
      - "8081:8080"
    env_file:
      - frontend.env
    networks:
      dev:
