name: Deploy

on:
  repository_dispatch:
    types:
      - deploy-test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Шаг 1: Копируем docker-compose на VPS
      - name: Upload docker-compose.test.yml to VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.test.yml"
          target: "/home/${{ secrets.VPS_USER }}/test/docker-compose.test.yml"

      # Шаг 2: Подключение к VPS
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}
      
     # Шаг 3: Подключение к VPS и запуск Docker Compose
      - name: Deploy Docker Compose on VPS
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} <<EOF
            cd /home/${{ secrets.VPS_USERNAME }}/test
            pwd
            cp docker-compose.test.yml .
            sudo docker compose down || true
            sudo docker rmi andreyparkh/my-calendar-frontend-pr
            sudo docker compose up -d

      # Шаг 4: Отправка статуса
      - name: Send success status
        if: success()
        run: echo "Deployment completed successfully."

      - name: Send failure status
        if: failure()
        run: echo "Deployment failed."